FROM ubuntu:25.04 as builder
RUN apt update
RUN apt install -y build-essential
# remove cache
RUN apt clean && rm -rf /var/lib/apt/lists/*
COPY hello.c /
RUN make hello

FROM alpine:latest
# install libc6-compat for glibc compatibility
RUN apk --no-cache add libc6-compat
COPY --from=builder /hello /hello
CMD ["/hello"]
