apiVersion: v1
kind: Pod
metadata:
  name: resource-limits-pod
  labels:
    app: resource-demo
spec:
  containers:
  - name: stress-test
    image: polinux/stress:latest
    command: ["stress"]
    args:
      - "--cpu"
      - "1"
      - "--vm"
      - "1"
      - "--vm-bytes"
      - "128M"
      - "--timeout"
      - "3600s"
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
