apiVersion: v1
kind: Pod
metadata:
  name: python-app
  labels:
    app: python
spec:
  containers:
  - name: python-app
    image: python:3.9-slim
    command: ["python", "-c"]
    args:
      - |
        import os
        import time
        print(f"App Name: {os.getenv('APP_NAME')}")
        print(f"Environment: {os.getenv('ENVIRONMENT')}")
        print(f"Version: {os.getenv('APP_VERSION')}")
        while True:
          time.sleep(30)
    env:
    - name: APP_NAME
      value: "MyPythonApp"
    - name: ENVIRONMENT
      value: "development"
    - name: APP_VERSION
      value: "1.0.0"
