apiVersion: v1
kind: Pod
metadata:
  name: probes-pod
  labels:
    app: probes-demo
spec:
  containers:
  - name: app
    image: busybox:latest
    command: ["/bin/sh", "-c"]
    args:
      - |
        # Crear archivos de estado
        mkdir -p /tmp/health

        # Iniciar como no listo
        echo "Starting application..."

        # Simular tiempo de inicialización (15 segundos)
        sleep 15

        # Marcar como listo
        touch /tmp/health/ready
        echo "Application is ready!"

        # Marcar como vivo
        touch /tmp/health/alive
        echo "Application is alive!"

        # Simular aplicación corriendo
        counter=0
        while [ $counter -lt 100 ]; do
          echo "Application running... iteration $counter"

          # Simular fallo después de 60 segundos
          if [ $counter -eq 20 ]; then
            echo "Simulating failure - removing alive marker"
            rm /tmp/health/alive
          fi

          sleep 3
          counter=$((counter + 1))
        done

    # Readiness probe - verifica si la aplicación está lista para recibir tráfico
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/health/ready
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3

    # Liveness probe - verifica si la aplicación está viva y funcionando
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/health/alive
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 3
